config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#index"
  resources :users, only: [:index, :show] do
    resources :posts do
      resources :comments,  only: [:new, :create, :destroy]
      resources :likes,  only: [:create] 
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # Guest user (not logged in)

    # Define abilities for different roles
    if user.admin?
      can :manage, :all # Admins can manage all resources
    else
      can :read, :all
      can :create, Post
      can :destroy, Post, author_id: user.id
      can :destroy, Comment, author_id: user.id

    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_save :increment_post_comments_counter

  private

  def increment_post_comments_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_save :increment_post_likes_counter

  private

  def increment_post_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments, dependent: :destroy
  has_many :likes

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_comments
    comments.includes(:author).order(created_at: :desc).limit(5)
  end

  after_save :increment_user_posts_counter

  private

  def increment_user_posts_counter
    author.increment!(:posts_counter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # , :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end

  def admin?
    role == 'admin'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected
  def configure_permitted_parameters
    puts 'Method being called'
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
  def after_sign_out_path_for(resource_or_scope)
    puts "Sign out called for #{resource_or_scope}"
    new_user_session_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
    def new
      @user = Post.find(params[:post_id])
      @post = Post.find(params[:post_id])
      @comment = Comment.new
    end
  
    def create
      @user = current_user
      @comment = @user.comments.build(comment_params)
      @comment.post_id = params[:post_id]
  
      if @comment.save
        flash[:success] = 'Comment created successfully'
      else
        flash[:error] = 'Something went wrong.'
        puts @comment.errors.full_messages # Check the server console for error messages
        render :new
      end
  
      redirect_to user_post_path(params[:user_id], @comment.post_id)
    end

    def destroy
      @comment = Comment.find(params[:id])
      authorize! :destroy, @comment # Authorize the action
      @post = @comment.post
      @post.decrement!(:comments_counter)
      @comment.destroy
      redirect_to user_post_path(params[:user_id], @comment.post_id), notice: 'Comment was successfully destroyed.'
    end
  
    private
  
    def comment_params
      params.require(:comment).permit(:body)
    end
  end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!
    def create
      logger.debug(params)
      @user = User.find(params[:user_id])
      @post = @user.posts.find(params[:post_id])
      @like = @post.likes.build
      @like.author = current_user
      if @like.save
        flash[:success] = 'Liked the post!'
      else
        flash[:error] = 'Something went wrong while liking the post.'
      end
  
      redirect_to user_post_path(@user, @post)
    end
  end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
    def index
      @user = User.find(params[:user_id])
      @posts = @user.posts.includes(comments: :author)
    end
  
    def show
      logger.debug(params)
      @user = User.find(params[:user_id])
      @post = @user.posts.find(params[:id])
      @comments = @post.comments
    end
  
    def new
      @user = current_user
      @post = Post.new
    end
  
    def create
      @post = current_user.posts.build(post_params)
      if @post.save
        redirect_to user_posts_path, notice: 'Post was successfully created.'
      else
        flash.now[:alert] = 'Something Wrong, Cannot create a new post'
        render :new
      end
    end

    def destroy
      @post = Post.find(params[:id])
      authorize! :destroy, @post
      @author = @post.author
      @author.decrement!(:posts_counter)
      @post.destroy
      if @post.destroy
        redirect_to user_posts_path(current_user), notice: 'post was successfully deleted.'
      else
        redirect_to redirect_url, alert: 'Failed to delete the post.'
      end
    end
  
    private
  
    def post_params
      params.require(:post).permit(:title, :text, :user_id)
    end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
    def index
      @users = User.all
    end
  
    def show
      @user = User.find(params[:id])
      @posts = @user.posts
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<section class="container mt-5">
  <div class="row justify-content-center align-items-center "> <!-- Center vertically using Flexbox -->
    <div class="col-6 border border-dark rounded-1  border-2 p-5">
    <h1 class="text-center">Add A Comment</h1>
        <% if flash[:error].present? %>
            <div class="alert alert-danger">
            <%= flash[:error] %>
            </div>
        <% end %>
      

      <%= form_with(model: @comment, url: user_post_comments_path(@user, @post)) do |form| %>

        <div class="form-group">
            <%= form.label :body, 'Comment' %>
            <%= form.text_area :body, class: 'form-control' %>
        </div>

        <div class="form-group mt-2">
          <%= form.submit 'Create Post', class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>

app/views/posts/index.html.erb
<section class="container">
    <%= render partial: 'shared/user', locals: { user: @user } %>
    <% @posts.each do |post| %>  
        <div class="row mt-4">
            <div class="col-lg-12 border border-dark">
                <div class="row">
                    <div class="col-lg-10">
                        <h4 class="pt-2"><%= link_to post.title, user_post_path(@user, post), class: "text-dark" %></h4>
                        <p class="mt-2"><%= truncate(post.text, length: 200, omission: '...') %></p>
                        <p class="d-flex justify-content-end"><%= link_to "Add Comment", new_user_post_comment_path(@user, post), class:"text-dark" %>, Comments <%= post.comments_counter %>, Likes <%= post.likes_counter%></p>
                    </div>
                    <div class="col-lg-2">
                        <p class="d-flex justify-content-end">
                           <%= render partial: 'shared/like', locals: { user: @user, post: post } %>
                        </p>
                        <% if post.author.id == current_user.id || current_user.admin? %>
                            <%= button_to 'Delete Post', user_post_path(post.author, post), method: :delete, class: 'btn btn-danger' %>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 border border-dark">
                <table class="table table-border">
                    <tbody>
                        <% post.comments.each do |comment| %>
                            <tr>
                                <td><%= comment.author.name %>: <%= comment.body %></td>
                                <td>
                                    <% if can? :destroy, comment %>
                                        <%= button_to 'Delete', user_post_comment_path(post.author, post, comment), method: :delete, class: 'btn btn-light text-danger btn-sm'%>
                                    <% end %>
                                </td>
                            </tr>
                        <% end %>
                    </tbody>
                </table>

            </div>
        </div>
    <% end %>
    <p class='pagination'>pagination</p>
</section>

app/views/posts/new.html.erb
<section class="container mt-5">
<%= render partial: 'shared/signout' %>
  <div class="row justify-content-center align-items-center "> <!-- Center vertically using Flexbox -->
    <div class="col-6 border border-dark rounded-1  border-2 p-5">
    <h1 class="text-center">Add new post</h1>
       <% if flash[:alert].present? %>
        <div class="alert alert-danger">
          <%= flash[:alert] %>
        </div>
      <% end %>
       

      <%= form_with(model: @post, url: user_posts_path) do |form| %>
        <div class="form-group">
          <%= form.label :title %>
          <%= form.text_field :title, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :text %>
          <%= form.text_area :text, class: 'form-control' %>
        </div>

        <%= form.hidden_field :author_id, value: current_user.id %>

        <div class="form-group mt-2">
          <%= form.submit 'Create Post', class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/posts/show.html.erb
<section class="container">
    <%= render partial: 'shared/signout' %>
    
    <div class="row mt-4">
        <div class="col-lg-12 border border-dark">
            <div class="row">
                <div class="col-lg-10">
                    <h4 class="pt-2">'<%= @post.title %>' by <%= @user.name %></h4>
                    <p class="mt-2"><%= @post.text %></p>
                    <p class="d-flex justify-content-end"><%= link_to "Add Comment", new_user_post_comment_path(current_user, @post), class:"text-dark" %>, Comments <%= @post.comments_counter %>, Likes <%= @post.likes_counter%></p>    
                </div>
                <div class="col-lg-2">
                     <p class="d-flex justify-content-end">
                        <%= render partial: 'shared/like', locals: { user: @user, post: @post } %>
                    </p>
                    <% if @post.author.id == current_user.id || current_user.admin? %>
                        <%= button_to 'Delete Post', user_post_path(@post.author, @post), method: :delete, class: 'btn btn-danger' %>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12 border border-dark">
            <table class="table table-border">
                <tbody>
                    <% @comments.each do |comment| %>
                        <tr>
                            <td><%= comment.author.name %>: <%= comment.body %></td>
                            <td>
                                <% if can? :destroy, comment %>
                                    <%= button_to 'Delete', user_post_comment_path(@post.author, @post, comment), method: :delete, class: 'btn btn-light text-danger btn-sm'%>
                                <% end %>
                            </td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>
</section>

app/views/shared/_like.html.erb
<%= form_with(url: user_post_likes_path(@user, post), method: :post) do |form| %>
    <%= form.hidden_field :post_id, value: post.id %>
    <%= form.submit "Like", class: "btn btn-primary" %>
<% end %>

app/views/shared/_signout.html.erb
<% if user_signed_in? %>
        <%= form_tag(destroy_user_session_path, method: :delete, class: "d-flex justify-content-center") do %>
          <%= submit_tag("Sign Out", class: "btn btn-danger") %>
        <% end %>
    <% end %>

app/views/shared/_user.html.erb
<div class="row mt-4">
<%= render partial: 'shared/signout' %>
    <div class="col-lg-2">
        <%= image_tag("default.jpg", alt: "Default", style: "width: 70%;") %>
    </div>
    <div class="col-lg-10 border border-dark d-flex align-items-center">
        <div class="user-lists w-100">
            <h2 class="text-dark"><%= @user.name %></h2>
            <p class="d-flex justify-content-end">Number Of posts <%= @user.posts_counter %></p>
        </div>
    </div>
</div>

app/views/users/index.html.erb
<section id="body-content" class="container">
    
    <%= render partial: 'shared/signout' %>
    
    <%= link_to "Create New Post", new_user_post_path(current_user.id), class: "btn btn-primary" %>

    <% @users.each do |user| %>
        <div class="row mt-4">
            <div class="col-lg-2">
                <%= image_tag("default.jpg", alt: "Default", style: "width: 70%;") %>
            </div>
            <div class="col-lg-10 border border-dark d-flex align-items-center">
                <div class="user-lists w-100">
                    <h2 class="text-dark"><%= link_to user.name, user_path(user) %></h2>
                    <p class="d-flex justify-content-end">Number Of posts <%= user.posts_counter %></p>
                </div>
            </div>
        </div>
    <% end %>
    
</section>

app/views/users/show.html.erb
<section id="body-content" class="container">
    <%= render partial: 'shared/user', locals: { user: @user } %>
    <div class="row mt-4">
        <div class="col-lg-12 border border-dark">
            <h4>Bio</h4>
            <p class="mt-2"><%= @user.bio %></p>
        </div>
    </div>

    <% @posts.each_with_index do |post, index| %>  
        <div class="row mt-4">
            <div class="col-lg-12 border border-dark">
                <h4 class="pt-2"><%= link_to "Post ##{index + 1}", user_post_path(@user, post), class: "text-dark" %></h4>
                <p class="mt-2"><%= truncate(post.text, length: 200, omission: '...') %></p>

                <p class="d-flex justify-content-end">
                   <%= render partial: 'shared/like', locals: { user: @user, post: post } %>
                </p>
                <p class="d-flex justify-content-end"><%= link_to "Add Comment", new_user_post_comment_path(@user, post), class:"text-primary" %>,  Comments <%= post.comments_counter %>, Likes <%= post.likes_counter%></p>
            </div>
        </div>
    <% end %>

    <div class="row mt-4 justify-content-center">
        <div class="col-lg-12 text-center">
            <%= link_to "View All Posts", user_posts_path(@user), class: "btn btn-primary" %>
        </div>
    </div>
</section>